---
- hosts: 172.31.1.193
  become: yes
  tasks:
  - name: i want to install git on redhot
    yum:
      name: git
      state: present
  - name: i want to install webserver on redhot
    yum:
      name: httpd
      state: present 
  - name: i want to start my webserver 
    service:
      name: httpd
      state: started 