---
- hosts: ubuntu
  become: yes
  tasks:
  - name: install git
    apt:
      name: git 

  - name: install tree
    apt:
      nameee: tree  
    ignore_error: yes 

  - name: install wget
    apt:
      name: wget  

  - name: install apache2
    apt:
      name: apache2  