---
- hosts: ubuntu
  become: yes
  gather_facts: yes 
  tasks:
  - name: i want to install webserver on ubuntu16
    apt:
      name: apache2
      state: present 
    notify: startwebserver
    when: ansible_on_family =="Debian"




  handlers:
  - name: startwebserver
    service:
      name: apache2
      state: started